site_name: Spud Wiki
site_url: https://github.com/SpikyTater/spud-wiki
repo_name: Spud Wiki
repo_url: https://github.com/SpikyTater/spud-wiki
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png